apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keycloak-rhbk
spec:
  generators:
    - list:
        elements:
          - name: 01_crunchy_postgres_operator
            repoURL: https://github.com/momoah/rhbk22/tree/main/01_crunchy_postgres_operator
            targetRevision: main
          - name: 02_rhbk_operator
            repoURL: https://github.com/momoah/rhbk22/tree/main/02_rhbk_operator
            targetRevision: main
          - name: 03_postgres_instance
            repoURL: https://github.com/momoah/rhbk22/tree/main/03_postgres_instance
            targetRevision: main
  template:
    metadata:
      name: '{{.name}}'
    spec:
      source:
        repoURL: '{{.repoURL}}'
        targetRevision: '{{.targetRevision}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'default'

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-rhbk
spec:
  source:
    repoURL: https://github.com/momoah/rhbk22.git       
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  syncPolicy:
    automated:
      prune: true
      syncOptions:
        - applyOutOfSyncOnly: true
    syncWave:
      phaseOrder:   # Specify the order of sync waves
        - phase: 1
          synchronization:
            resources:
              - 01_crunchy_postgres_operator
              - 02_rhbk_operator
        - phase: 2
          synchronization:
            resources:
              - 03_postgres_instance
#        - phase: 3
#          synchronization:
#            resources:
#              - my-app5
#        - phase: 4
#          synchronization:
#            resources:
#              - my-app6
#        - phase: 5
#          synchronization:
#            resources: []   # You can leave empty if no applications need to be synced in this phase
#        - phase: 6
#          synchronization:
#            resources: []   # Similarly, for the 6th phase
#
