apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01_create_keycloak_instance.yaml
  - 02_create_keycloak_route.yaml   
  - 03_create_keycloak_realm.yaml

patches:
  - target:
      kind: Route
      name: keycloak-admin-route
    patch: |-
      - op: replace
        path: /metadata/name
        value: keycloak-rhbk.apps.${CLUSTER_NAME}
