apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00_argocd_namespace.yaml  
  - 01_argocd_operatorgroup.yaml  
  - 02_argocd_subscription.yaml  
  - 03_argocd_rbac.yaml  
  - 04_openshift-gitops-instance.yaml
