apiVersion: batch/v1
kind: Job
metadata:
  name: rhbk-child-create-keycloak-secrets
spec:
  template:
    metadata:
      name: rhbk-child-create-keycloak-secrets
    spec:
      containers:
      - name: rhbk-child-rhbk-operator-containers
        image: quay.io/openshift/origin-cli:4.15
        command: ["/bin/bash", "-c"]
        args: 
          - |
            oc project rhbk
            oc create secret generic keycloak-db-secret \
            --from-literal=username="$(oc get secret -n rhbk postgresdb-pguser-keycloak -o go-template='{{.data.user | base64decode }}')" \
            --from-literal=password="$(oc get secret -n rhbk postgresdb-pguser-keycloak -o go-template='{{.data.password | base64decode }}')"
            #oc create secret tls keycloak-tls-secret --cert ./certificate.pem --key ./key.pem -n rhbk
            #oc create secret generic keycloak-truststore-secret --from-file=./truststore.jks -n rhbk
      restartPolicy: Never
